# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfef5834226eb9253460c649e9f58ea8709babca999a5b24452a733659ad8ec3ee671b61c603c3436a0d7626887b067ad9f90df45ca700b465b081acea5c6448

test:
  secret_key_base: 06bb172ac32b4f344c63b11534f03f93838e0ccda53557cdbc6aaeaee79ae57f97857d68f2755d2ef0f653247d147b0b0f398c525f0c3718b0a596bbdb246900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
